(provide 'init-keymaps)

; Global Key Mappings
(global-set-key (kbd "M-x")       'helm-M-x)
(global-set-key (kbd "M-q")       'save-buffers-kill-emacs)
(global-set-key (kbd "M-a")       'mark-whole-buffer)
(global-set-key (kbd "M-c")       'cua-copy-region)
(global-set-key (kbd "M-v")       'cua-paste)
(global-set-key (kbd "C-<left>")  'windmove-left)
(global-set-key (kbd "C-<down>")  'windmove-down)
(global-set-key (kbd "C-<up>")    'windmove-up)
(global-set-key (kbd "C-<right>") 'windmove-right)
;(global-set-key (kbd "C-<tab>")   'neotree-toggle)
(global-set-key (kbd "C-<tab>")   'sr-speedbar-toggle)
(global-set-key (kbd "<f2>")      'save-buffer)
(global-set-key (kbd "<f3>")      'toggle-truncate-lines)
(global-set-key (kbd "<f4>")      'delete-window)
(global-set-key (kbd "<f8>")      'find-tag)
(global-set-key (kbd "<f9>")      'pop-tag-mark)
(global-set-key (kbd "<f10>")     'helm-etags-select)
(global-set-key (kbd "<tab>")     'indent-or-expand)
